apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"

  SMTP_USER: "valentinaelizabeth1816@gmail.com"
  SMTP_PASS: "iybbokkssviufbmo"

  SMTP_FROM: "valentinaelizabeth1816@gmail.com"
  ADMIN_EMAIL: "valentinaelizabeth1816@gmail.com"
