apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
type: Opaque
stringData:
  SMTP_USER: valentinaelizabeth1816@gmail.com         # tu_correo@gmail.com
  SMTP_PASS: iybbokkssviufbmo                     # c2VndXJvX3Bhc3N3b3JkX2FxdWk=         # seguro_password_aqui
  ADMIN_EMAIL: valentinaelizabeth1816@gmail.com
